baseURL = "/"
languageCode = "en-us"
title = "Kat Tow"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    description = "Portfolio of Kat Tow"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "img/pug.gif"
    logo-alt = "Kat Tow"
    email = "kattow88@gmail.com"
    twitter = "akattow"
    linkedin = "kattow"
    resume = "ResumeTow.pdf"


[[menu.main]]
    name = "home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "about"
    url  = "/about"
    weight = 2

[[menu.main]]
    name = "my work"
    url  = "/work"
    weight = 2

[[menu.main]]
    name = "resume"
    url  = "/resume"
    weight = 3